Update dayzserver

diff --git a/script/dayzserver b/script/dayzserver
--- a/script/dayzserver
+++ b/script/dayzserver
@@ -27,6 +27,14 @@ if [ "${ansi}" != "off" ]; then
         creeol="\r\033[K"
 fi
 
+fn_checkroot_dayz(){
+	if [ "$(whoami)" == "root" ]; then
+	  printf "[ ${red}FAIL${default} ] ${yellow}Do NOT run this script as root!\n"
+	  printf "\tSwitch to the dayz user!${default}\n"
+	  exit 1
+	fi
+}
+
 fn_checktmux(){
 	if [ -n "${TMUX}" ]; then
 		printf "[ ${red}FAIL${default} ] The Script creates a tmux session when starting the server.\n"
@@ -61,9 +69,8 @@ fn_loadconfig_dayz(){
 	defaultservername=$(grep -rwi ${HOME}/serverfiles/serverDZ.cfg -e 'EXAMPLE NAME')
 	if [ "${defaultservername}" != "" ]; then
 		printf "[ ${magenta}SERVER${default} ] Servername is set on default! 'EXAMPLE NAME'\n\n"
-		#read -p "Enter a new Servername: " servername
-		#sed -i "/hostname/ s/EXAMPLE NAME/${servername}/" "${HOME}/serverfiles/serverDZ.cfg"
-		sed -i "/hostname/ s/EXAMPLE NAME/teste/" "${HOME}/serverfiles/serverDZ.cfg"
+		read -p "Enter a new Servername: " servername
+		sed -i "/hostname/ s/EXAMPLE NAME/${servername}/" "${HOME}/serverfiles/serverDZ.cfg"
 	fi
 	# battleye config and rconpassword setup
 	if [ ! -f "${HOME}/serverfiles/battleye/beserver_x64.cfg" ]; then
@@ -181,10 +188,9 @@ fn_steamlogin_dayz(){
 	source ${HOME}/.steamlogin
 	if [ "${steamlogin}" == "" ]; then
 		printf "\n[ ${magenta}STEAM${default} ] "
-		#read -p "Please type in your Steamlogin (username): " steamname
+		read -p "Please type in your Steamlogin (username): " steamname
 		sleep 0.5
-		#sed -i "/steamlogin/ s/=/=$steamname/" ${HOME}/.steamlogin
-		sed -i "/steamlogin/ s/=/=anonymous/" ${HOME}/.steamlogin
+		sed -i "/steamlogin/ s/=/=$steamname/" ${HOME}/.steamlogin
 		sleep 0.5
 		source ${HOME}/.steamlogin
 	fi
@@ -426,7 +432,7 @@ done
 
 # Shows LinuxGSM usage
 fn_opt_usage(){
-        printf "\nDayZ 1.15 Exp - Linux Game Server - Version: "${version}""
+        printf "\nDayZ Experimental - Linux Game Server - Version: "${version}""
 	printf "\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=1517338673"
 	printf "\nUsage:${lightblue} $0 [command]${default}\n\n"
         printf "${lightyellow}Commands${default}\n"
@@ -444,6 +450,7 @@ fn_opt_usage(){
 }
 
 # start functions
+fn_checkroot_dayz
 fn_checktmux
 fn_checkscreen
 
